[package]
name = "elrond_trade_offer-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.elrond_trade_offer]
path = ".."

[dependencies.elrond-wasm]
version = "0.29.3"

[dependencies.elrond-wasm-debug]
version = "0.29.3"